#!/bin/bash -l

#$ -l h_rt=48:00:00

#$ -m e

#$ -j y

#$ -N on_off_RL_from_observations_rodent_domain_adaptation_AWAC_Q_lambda_TB

#$ -V

#$ -pe omp 4
#$ -l mem_per_core=4G

module load miniconda

conda activate /project/onr/vgiammar/RL_env
python main.py --mode on_off_RL_from_observations --policy AWAC_Q_lambda_TB --max_iter 100 --data_set rodent --intrinsic_reward 0.01 --domain_adaptation --seed $1
